# Quick pandas tutorial

Based on the following pandas tutorial from DataCamp:
https://www.datacamp.com/tutorial/pandas

## Locating and reading a csv file and data exploration

Add the location of the file to read, and read using pandas pd.read_csv() command

In [5]:
import pandas as pd

In [7]:
# File location
path_to_file = ('Z:/Home/ezarazua/Python data/google-play-store-11-2018.csv')
# Read the file *.csv type
google_data = pd.read_csv(path_to_file)

## Data exploration

In [ ]:
# See the size of the data set
print(f'Shape of data frame: {google_data.shape}')

See the type of data in columns

In [ ]:
print('General information of data frame:') 
google_data.info()

In [29]:
# Show descriptive statistics of the data frame:
google_data.describe()

,reviews,ratings,min_installs,score,ratings_per_day,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
count,6.268300e+04,6.268300e+04,6.269400e+04,62683.000000,62694.000000,62694.000000,6.269400e+04,6.269400e+04,6.269400e+04,6.269400e+04,6.269400e+04
mean,1.529843e+04,4.936328e+04,2.035663e+06,4.221624,38.620506,0.414998,3.078124e+03,1.211618e+03,3.094328e+03,7.227599e+03,3.474295e+04
std,2.261505e+05,7.690255e+05,2.386872e+07,0.815517,430.422770,3.793236,6.050231e+04,2.193403e+04,5.230251e+04,1.117066e+05,5.368042e+05
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.600000e+01,4.100000e+01,1.000000e+03,4.100497,0.000000,0.000000,2.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,2.800000e+01
50%,1.440000e+02,3.980000e+02,5.000000e+04,4.403101,0.000000,0.000000,2.400000e+01,9.000000e+00,2.300000e+01,4.700000e+01,2.640000e+02
75%,1.500000e+03,4.488000e+03,5.000000e+05,4.637007,6.000000,0.000000,3.070000e+02,1.090000e+02,2.840000e+02,6.090000e+02,2.933000e+03
max,2.205377e+07,8.128486e+07,1.000000e+09,5.000000,40526.000000,369.990000,9.658715e+06,3.368101e+06,7.164984e+06,1.222342e+07,5.295266e+07

In [32]:
# Show descriptive statistics of a column from the data frame using []:
google_data[['price']].describe()

              price
count  62694.000000
mean       0.414998
std        3.793236
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max      369.990000

In [26]:
# Show descriptive statistics of 2 or more columns from the data frame using [[]]:
google_data[['price', 'score','ratings']].describe()

              price         score       ratings
count  62694.000000  62683.000000  6.268300e+04
mean       0.414998      4.221624  4.936328e+04
std        3.793236      0.815517  7.690255e+05
min        0.000000      0.000000  0.000000e+00
25%        0.000000      4.100497  4.100000e+01
50%        0.000000      4.403101  3.980000e+02
75%        0.000000      4.637007  4.488000e+03
max      369.990000      5.000000  8.128486e+07

In [34]:
# see the titles of each column
print(f'Column titles of data frame: {google_data.columns}')

Column titles of data frame: Index(['app_id', 'title', 'reviews', 'ratings', 'min_installs', 'score',
       'offers_iap', 'ad_supported', 'released', 'ratings_per_day', 'genre',
       'genre_id', 'price', 'rating_one_star', 'rating_two_star',
       'rating_three_star', 'rating_four_star', 'rating_five_star'],
      dtype='object')

In [56]:
# Show the first 5 rows of the data set
google_data.head()

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
0,com.prettyteengames.royal.princess.wedding.mak...,Royal Princess Wedding Makeover and Dress Up,375.0,1023.0,100000,4.179863,True,True,2017-12-20,3,Casual,GAME_CASUAL,0.0,115,31,98,90,689
1,com.MayGreenStudio.dressup,Momo's Dressup,13492.0,25974.0,1000000,4.711096,False,True,2017-03-07,42,Casual,GAME_CASUAL,0.0,673,213,806,2561,21721
2,air.theflash.f2game.PrettyGirl23,Princess Pretty Girl,1974.0,4610.0,500000,4.295445,False,True,2015-01-18,3,Casual,GAME_CASUAL,0.0,382,206,287,528,3207
3,air.com.dressupone.animeschooluniforms,Anime School Uniforms,2586.0,6081.0,500000,4.209505,False,True,2013-08-20,3,Casual,GAME_CASUAL,0.0,628,193,524,668,4068
4,air.theflash.f2game.PrettyGirl7,Wedding Pretty girl,1409.0,3728.0,500000,4.195011,False,True,2014-09-01,2,Casual,GAME_CASUAL,0.0,358,185,300,414,2471

In [58]:
# Show the last 5 rows of the data set
google_data.tail()

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
62689,com.yunbu.balala.magicdress3.free,Magic Princess Dress 3,2520.0,5751.0,500000,4.362198,True,True,2017-11-08,15,Casual,GAME_CASUAL,0.0,388,148,511,650,4054
62690,air.com.dressupone.lateforclass,"Dress Up Games, Late For Class",5019.0,13362.0,1000000,4.105823,False,True,2013-11-12,7,Casual,GAME_CASUAL,0.0,1444,724,1247,1506,8441
62691,com.magicdress.cinderella.ice.princess.free,Magic Princess Dress 2,2893.0,7119.0,500000,4.192864,True,True,2017-02-23,11,Casual,GAME_CASUAL,0.0,622,250,797,914,4536
62692,com.gamesforgirlsfree.animeprincess,Anime Princess Dress Up,1382.0,3230.0,100000,4.479257,False,True,2017-08-07,6,Casual,GAME_CASUAL,0.0,174,51,238,357,2410
62693,com.ninepixel.whitehorseprincessandroid,White Horse Princess Dress Up,1537.0,5855.0,1000000,4.002733,False,True,2013-04-02,2,Casual,GAME_CASUAL,0.0,746,390,552,581,3586

In [43]:
# Count the numbers of cells without data with *.isnull() and *.sum() function
print('Number of missing data per column:\n', google_data.isnull().sum())

Number of missing data per column:
 app_id                 0
title                  0
reviews               11
ratings               11
min_installs           0
score                 11
offers_iap             0
ad_supported           0
released             846
ratings_per_day        0
genre                  1
genre_id               1
price                  0
rating_one_star        0
rating_two_star        0
rating_three_star      0
rating_four_star       0
rating_five_star       0
dtype: int64

In [51]:
# Count the total number of cells without data with double *.sum().sum()
print('\nTotal number of empty cells:\n', google_data.isnull().sum().sum())

Total number of empty cells:
 881

## Working with data, sorting, filtering, saving.

Sorting the data by gender_id and title in ascending order

In [145]:
# Sorting the data set by gender_id and title in ascending order in a new dataframe
genre_sort = google_data.sort_values(by=['genre_id', "title"], ascending=True)
# Reset the index for the new sorted data
genre_sort.reset_index(drop=True, inplace=True)
# Show the head of the sorted data set
genre_sort.head()

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
0,com.Flower.Arrangement.Ideas,3000 Flower Arrangements Ideas,15.0,74.0,10000,4.716216,False,True,2018-09-25,1,Art & Design,ART_AND_DESIGN,0.0,0,2,2,11,59
1,qarlab.logomaker3d.d3logomaker.logomakerfree,3D Logo Maker,12.0,25.0,1000,3.840000,False,True,2018-10-03,0,Art & Design,ART_AND_DESIGN,0.0,6,1,1,0,17
2,com.zotoappx.threeDLogoMaker,3D Logo Maker,326.0,837.0,100000,4.299881,False,True,2018-05-26,5,Art & Design,ART_AND_DESIGN,0.0,65,20,79,108,565
3,com.kingship.logomaker3d,"3D Logo Maker - Logo Designer , Logo Generator",9.0,17.0,1000,4.235294,False,True,2018-07-18,0,Art & Design,ART_AND_DESIGN,0.0,1,2,1,1,12
4,com.logocreator.logodesigner.logo3dpro.maker,3D Logo Maker Pro,177.0,469.0,10000,4.586354,False,True,2018-02-25,1,Art & Design,ART_AND_DESIGN,0.0,19,2,20,72,356

Note that the index now starts at 0 and the values are ordered by genre_id and then by title name.

Filter data by creating a new dataframe by selecting and sorting the data with more than 10 million 5-stars rating.
It will need to create a new dataframe using a boolean function. The boolean command will be used to select the data with more than 10 million 5-stars from the dataset.

In [160]:
# Select the rows with more than 10E+7 5-stars
top_5_stars = google_data[google_data['rating_five_star'] > 1E+7]

In [162]:
# Sort the selected data and re-index
top_5_stars = top_5_stars.sort_values(by=['rating_five_star'], ascending=False)
top_5_stars.reset_index(drop=True, inplace=True)

In [176]:
# Verify data selection and index reset
top_5_stars[['title','rating_five_star']]

                                                title  rating_five_star
0                                  WhatsApp Messenger          52952655
1                                           Instagram          51812869
2                                            Facebook          48869643
3                                      Clash of Clans          37224307
4            Messenger – Text and Video Chat for Free          35988340
5             Clean Master- Space Cleaner & Antivirus          34198207
6                                      Subway Surfers          21365844
7                                             YouTube          21044178
8   Security Master - Antivirus, VPN, AppLock, Boo...          19663882
9                                        Clash Royale          18859511
10                                   Candy Crush Saga          16186958
11        UC Browser - Fast Download Private & Secure          13325844
12    360 Security - Free Antivirus, Booster, Cleaner          12699713
13                                     My Talking Tom          11590854
14                                        8 Ball Pool          11190581
15                                           Snapchat          11091500

## Correlations between columns

In [198]:
# Selection of columns with numbers to find correlations among them.
top_5_stars[['ratings', 'score', 'min_installs']].corr()

               ratings     score  min_installs
ratings       1.000000 -0.330332      0.637305
score        -0.330332  1.000000     -0.515500
min_installs  0.637305 -0.515500      1.000000